blank_issues_enabled: false
contact_links:
  - name: Developer Documentation
    url: https://remora.github.io/Remora.Discord/
    about: Need documentation and examples for the API? Head over to Discord's developer documentation.
  - name: Discord Server
    url: https://discord.gg/dyYmwashVs
    about: Need help with the library? Talk to us in our Discord server.
